export const SAVE_DATA = "SAVE_DATA";
export const TEST_SAGA = "TEST_SAGA";

export const STORE_DEMO_SAGA = "STORE_DEMO_SAGA";
export const DISPLAY_FROM_API = "DISPLAY_FROM_API";

export const DETAIL_API = "DETAIL_API";
export const DISPLAY_DETAIL = "DISPLAY_DETAIL";

export const types = {
    SAVE_DATA: "SAVE_DATA",
    TEST_SAGA: "TEST_SAGA",

    STORE_DEMO_SAGA: "STORE_DEMO_SAGA",
    DISPLAY_FROM_API: "DISPLAY_FROM_API",

    DETAIL_API:"DETAIL_API",
    DISPLAY_DETAIL:"DISPLAY_DETAIL",

    DELETE_SAGA:"DELETE_SAGA",
    UPDATE_SAGA:"UPDATE_SAGA"

}